--
-- PostgreSQL database dump
--

-- Dumped from database version 15.7
-- Dumped by pg_dump version 15.7

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: timescaledb; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS timescaledb WITH SCHEMA public;


--
-- Name: EXTENSION timescaledb; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION timescaledb IS 'Enables scalable inserts and complex queries for time-series data (Community Edition)';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: sensor_measurements; Type: TABLE; Schema: public; Owner: irrigation_user
--

CREATE TABLE public.sensor_measurements (
    id bigint NOT NULL,
    device_name character varying(100) NOT NULL,
    topic character varying(255),
    temperature double precision,
    humidity double precision,
    linkquality integer,
    battery integer,
    max_temperature double precision,
    min_temperature double precision,
    temperature_sensitivity double precision,
    temperature_calibration double precision,
    temperature_sampling integer,
    temperature_unit character varying(20),
    humidity_calibration double precision,
    soil_moisture double precision,
    soil_calibration double precision,
    soil_sampling integer,
    soil_warning integer,
    dry boolean,
    raw_data jsonb,
    "timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.sensor_measurements OWNER TO irrigation_user;

--
-- Name: _hyper_2_1_chunk; Type: TABLE; Schema: _timescaledb_internal; Owner: irrigation_user
--

CREATE TABLE _timescaledb_internal._hyper_2_1_chunk (
    CONSTRAINT constraint_1 CHECK ((("timestamp" >= '2026-05-07 00:00:00+00'::timestamp with time zone) AND ("timestamp" < '2026-05-14 00:00:00+00'::timestamp with time zone)))
)
INHERITS (public.sensor_measurements);


ALTER TABLE _timescaledb_internal._hyper_2_1_chunk OWNER TO irrigation_user;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: irrigation_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO irrigation_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: irrigation_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: irrigation_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO irrigation_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: irrigation_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: irrigation_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO irrigation_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: irrigation_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: irrigation_user
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO irrigation_user;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: irrigation_user
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO irrigation_user;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: irrigation_user
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: irrigation_user
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: irrigation_user
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO irrigation_user;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: irrigation_user
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: devices; Type: TABLE; Schema: public; Owner: irrigation_user
--

CREATE TABLE public.devices (
    id integer NOT NULL,
    zigbee_id character varying(100) NOT NULL,
    name character varying(120) NOT NULL,
    device_type character varying(40) NOT NULL,
    greenhouse_id integer NOT NULL,
    active boolean NOT NULL,
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.devices OWNER TO irrigation_user;

--
-- Name: devices_id_seq; Type: SEQUENCE; Schema: public; Owner: irrigation_user
--

ALTER TABLE public.devices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.devices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: irrigation_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO irrigation_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: irrigation_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: irrigation_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO irrigation_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: irrigation_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: irrigation_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO irrigation_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: irrigation_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: irrigation_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO irrigation_user;

--
-- Name: greenhouse_config; Type: TABLE; Schema: public; Owner: irrigation_user
--

CREATE TABLE public.greenhouse_config (
    id integer NOT NULL,
    name character varying(120) NOT NULL,
    location character varying(200) NOT NULL,
    controller_ip inet,
    controller_username character varying(100) NOT NULL,
    controller_password character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    season character varying(100) NOT NULL,
    feature_layout boolean NOT NULL,
    feature_meteostation boolean NOT NULL,
    feature_plants boolean NOT NULL,
    feature_watering_liters boolean NOT NULL,
    feature_smart_suggestions boolean NOT NULL
);


ALTER TABLE public.greenhouse_config OWNER TO irrigation_user;

--
-- Name: greenhouse_config_id_seq; Type: SEQUENCE; Schema: public; Owner: irrigation_user
--

ALTER TABLE public.greenhouse_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.greenhouse_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: greenhouses; Type: TABLE; Schema: public; Owner: irrigation_user
--

CREATE TABLE public.greenhouses (
    id character varying NOT NULL,
    name character varying(120) NOT NULL,
    description text,
    location character varying(200),
    mqtt_broker character varying(120) NOT NULL,
    mqtt_port integer NOT NULL,
    mqtt_username character varying(120),
    mqtt_password text,
    active boolean NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.greenhouses OWNER TO irrigation_user;

--
-- Name: path_cells; Type: TABLE; Schema: public; Owner: irrigation_user
--

CREATE TABLE public.path_cells (
    id bigint NOT NULL,
    "row" integer NOT NULL,
    "column" integer NOT NULL,
    description character varying(200),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT path_cells_column_check CHECK (("column" >= 0)),
    CONSTRAINT path_cells_row_check CHECK (("row" >= 0))
);


ALTER TABLE public.path_cells OWNER TO irrigation_user;

--
-- Name: path_cells_id_seq; Type: SEQUENCE; Schema: public; Owner: irrigation_user
--

ALTER TABLE public.path_cells ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.path_cells_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plants; Type: TABLE; Schema: public; Owner: irrigation_user
--

CREATE TABLE public.plants (
    id character varying NOT NULL,
    name character varying(100) NOT NULL,
    variety character varying(100),
    planting_date date NOT NULL,
    watering_frequency integer NOT NULL,
    watering_duration integer NOT NULL,
    water_amount_ml integer,
    harvest_date_estimate date,
    harvest_quantity_estimate double precision,
    location_row integer NOT NULL,
    location_column integer NOT NULL,
    location_description character varying(200),
    notes text,
    active boolean NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.plants OWNER TO irrigation_user;

--
-- Name: sensor_data; Type: TABLE; Schema: public; Owner: irrigation_user
--

CREATE TABLE public.sensor_data (
    id bigint NOT NULL,
    device_name character varying(100) NOT NULL,
    topic character varying(255),
    temperature double precision,
    humidity double precision,
    linkquality integer,
    battery integer,
    max_temperature double precision,
    min_temperature double precision,
    temperature_sensitivity double precision,
    temperature_calibration double precision,
    temperature_sampling integer,
    temperature_unit character varying(20),
    humidity_calibration double precision,
    soil_moisture double precision,
    soil_calibration double precision,
    soil_sampling integer,
    soil_warning integer,
    dry boolean,
    raw_data jsonb,
    "timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.sensor_data OWNER TO irrigation_user;

--
-- Name: sensor_data_id_seq; Type: SEQUENCE; Schema: public; Owner: irrigation_user
--

CREATE SEQUENCE public.sensor_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sensor_data_id_seq OWNER TO irrigation_user;

--
-- Name: sensor_data_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: irrigation_user
--

ALTER SEQUENCE public.sensor_data_id_seq OWNED BY public.sensor_data.id;


--
-- Name: sensor_measurements_id_seq; Type: SEQUENCE; Schema: public; Owner: irrigation_user
--

CREATE SEQUENCE public.sensor_measurements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sensor_measurements_id_seq OWNER TO irrigation_user;

--
-- Name: sensor_measurements_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: irrigation_user
--

ALTER SEQUENCE public.sensor_measurements_id_seq OWNED BY public.sensor_measurements.id;


--
-- Name: sensor_metrics_5m; Type: VIEW; Schema: public; Owner: irrigation_user
--

CREATE VIEW public.sensor_metrics_5m AS
 SELECT public.time_bucket('00:05:00'::interval, sensor_measurements."timestamp") AS bucket,
    sensor_measurements.device_name,
    avg(sensor_measurements.temperature) AS avg_temperature,
    min(sensor_measurements.temperature) AS min_temperature,
    max(sensor_measurements.temperature) AS max_temperature,
    avg(sensor_measurements.humidity) AS avg_humidity,
    avg(sensor_measurements.soil_moisture) AS avg_soil_moisture,
    avg(sensor_measurements.battery) AS avg_battery,
    count(*) AS sample_count
   FROM public.sensor_measurements
  GROUP BY (public.time_bucket('00:05:00'::interval, sensor_measurements."timestamp")), sensor_measurements.device_name
  ORDER BY (public.time_bucket('00:05:00'::interval, sensor_measurements."timestamp")) DESC;


ALTER TABLE public.sensor_metrics_5m OWNER TO irrigation_user;

--
-- Name: watering_cycle; Type: TABLE; Schema: public; Owner: irrigation_user
--

CREATE TABLE public.watering_cycle (
    id character varying NOT NULL,
    scheduled_time timestamp without time zone NOT NULL,
    duration integer NOT NULL,
    description text,
    device character varying NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now(),
    status character varying NOT NULL,
    executed_at timestamp without time zone,
    result text,
    plan_id character varying
);


ALTER TABLE public.watering_cycle OWNER TO irrigation_user;

--
-- Name: watering_plans; Type: TABLE; Schema: public; Owner: irrigation_user
--

CREATE TABLE public.watering_plans (
    id character varying NOT NULL,
    name character varying(120) NOT NULL,
    description text,
    start_date date,
    end_date date,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now(),
    active boolean NOT NULL,
    greenhouse_config_id integer
);


ALTER TABLE public.watering_plans OWNER TO irrigation_user;

--
-- Name: _hyper_2_1_chunk id; Type: DEFAULT; Schema: _timescaledb_internal; Owner: irrigation_user
--

ALTER TABLE ONLY _timescaledb_internal._hyper_2_1_chunk ALTER COLUMN id SET DEFAULT nextval('public.sensor_measurements_id_seq'::regclass);


--
-- Name: _hyper_2_1_chunk timestamp; Type: DEFAULT; Schema: _timescaledb_internal; Owner: irrigation_user
--

ALTER TABLE ONLY _timescaledb_internal._hyper_2_1_chunk ALTER COLUMN "timestamp" SET DEFAULT CURRENT_TIMESTAMP;


--
-- Name: _hyper_2_1_chunk created_at; Type: DEFAULT; Schema: _timescaledb_internal; Owner: irrigation_user
--

ALTER TABLE ONLY _timescaledb_internal._hyper_2_1_chunk ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;


--
-- Name: sensor_data id; Type: DEFAULT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.sensor_data ALTER COLUMN id SET DEFAULT nextval('public.sensor_data_id_seq'::regclass);


--
-- Name: sensor_measurements id; Type: DEFAULT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.sensor_measurements ALTER COLUMN id SET DEFAULT nextval('public.sensor_measurements_id_seq'::regclass);


--
-- Data for Name: hypertable; Type: TABLE DATA; Schema: _timescaledb_catalog; Owner: irrigation_user
--



--
-- Data for Name: chunk; Type: TABLE DATA; Schema: _timescaledb_catalog; Owner: irrigation_user
--



--
-- Data for Name: dimension; Type: TABLE DATA; Schema: _timescaledb_catalog; Owner: irrigation_user
--



--
-- Data for Name: dimension_slice; Type: TABLE DATA; Schema: _timescaledb_catalog; Owner: irrigation_user
--



--
-- Data for Name: chunk_constraint; Type: TABLE DATA; Schema: _timescaledb_catalog; Owner: irrigation_user
--



--
-- Data for Name: chunk_index; Type: TABLE DATA; Schema: _timescaledb_catalog; Owner: irrigation_user
--



--
-- Data for Name: compression_chunk_size; Type: TABLE DATA; Schema: _timescaledb_catalog; Owner: irrigation_user
--



--
-- Data for Name: compression_settings; Type: TABLE DATA; Schema: _timescaledb_catalog; Owner: irrigation_user
--



--
-- Data for Name: continuous_agg; Type: TABLE DATA; Schema: _timescaledb_catalog; Owner: irrigation_user
--



--
-- Data for Name: continuous_agg_migrate_plan; Type: TABLE DATA; Schema: _timescaledb_catalog; Owner: irrigation_user
--



--
-- Data for Name: continuous_agg_migrate_plan_step; Type: TABLE DATA; Schema: _timescaledb_catalog; Owner: irrigation_user
--



--
-- Data for Name: continuous_aggs_bucket_function; Type: TABLE DATA; Schema: _timescaledb_catalog; Owner: irrigation_user
--



--
-- Data for Name: continuous_aggs_hypertable_invalidation_log; Type: TABLE DATA; Schema: _timescaledb_catalog; Owner: irrigation_user
--



--
-- Data for Name: continuous_aggs_invalidation_threshold; Type: TABLE DATA; Schema: _timescaledb_catalog; Owner: irrigation_user
--



--
-- Data for Name: continuous_aggs_materialization_invalidation_log; Type: TABLE DATA; Schema: _timescaledb_catalog; Owner: irrigation_user
--



--
-- Data for Name: continuous_aggs_watermark; Type: TABLE DATA; Schema: _timescaledb_catalog; Owner: irrigation_user
--



--
-- Data for Name: metadata; Type: TABLE DATA; Schema: _timescaledb_catalog; Owner: irrigation_user
--



--
-- Data for Name: tablespace; Type: TABLE DATA; Schema: _timescaledb_catalog; Owner: irrigation_user
--



--
-- Data for Name: bgw_job; Type: TABLE DATA; Schema: _timescaledb_config; Owner: irrigation_user
--



--
-- Data for Name: _hyper_2_1_chunk; Type: TABLE DATA; Schema: _timescaledb_internal; Owner: irrigation_user
--



--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: irrigation_user
--



--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: irrigation_user
--



--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: irrigation_user
--



--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: irrigation_user
--



--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: irrigation_user
--



--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: irrigation_user
--



--
-- Data for Name: devices; Type: TABLE DATA; Schema: public; Owner: irrigation_user
--



--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: irrigation_user
--



--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: irrigation_user
--



--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: irrigation_user
--



--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: irrigation_user
--



--
-- Data for Name: greenhouse_config; Type: TABLE DATA; Schema: public; Owner: irrigation_user
--



--
-- Data for Name: greenhouses; Type: TABLE DATA; Schema: public; Owner: irrigation_user
--



--
-- Data for Name: path_cells; Type: TABLE DATA; Schema: public; Owner: irrigation_user
--



--
-- Data for Name: plants; Type: TABLE DATA; Schema: public; Owner: irrigation_user
--



--
-- Data for Name: sensor_data; Type: TABLE DATA; Schema: public; Owner: irrigation_user
--



--
-- Data for Name: sensor_measurements; Type: TABLE DATA; Schema: public; Owner: irrigation_user
--



--
-- Data for Name: watering_cycle; Type: TABLE DATA; Schema: public; Owner: irrigation_user
--



--
-- Data for Name: watering_plans; Type: TABLE DATA; Schema: public; Owner: irrigation_user
--



--
-- Name: chunk_constraint_name; Type: SEQUENCE SET; Schema: _timescaledb_catalog; Owner: irrigation_user
--

SELECT pg_catalog.setval('_timescaledb_catalog.chunk_constraint_name', 1, false);


--
-- Name: chunk_id_seq; Type: SEQUENCE SET; Schema: _timescaledb_catalog; Owner: irrigation_user
--

SELECT pg_catalog.setval('_timescaledb_catalog.chunk_id_seq', 1, true);


--
-- Name: continuous_agg_migrate_plan_step_step_id_seq; Type: SEQUENCE SET; Schema: _timescaledb_catalog; Owner: irrigation_user
--

SELECT pg_catalog.setval('_timescaledb_catalog.continuous_agg_migrate_plan_step_step_id_seq', 1, false);


--
-- Name: dimension_id_seq; Type: SEQUENCE SET; Schema: _timescaledb_catalog; Owner: irrigation_user
--

SELECT pg_catalog.setval('_timescaledb_catalog.dimension_id_seq', 2, true);


--
-- Name: dimension_slice_id_seq; Type: SEQUENCE SET; Schema: _timescaledb_catalog; Owner: irrigation_user
--

SELECT pg_catalog.setval('_timescaledb_catalog.dimension_slice_id_seq', 1, true);


--
-- Name: hypertable_id_seq; Type: SEQUENCE SET; Schema: _timescaledb_catalog; Owner: irrigation_user
--

SELECT pg_catalog.setval('_timescaledb_catalog.hypertable_id_seq', 2, true);


--
-- Name: bgw_job_id_seq; Type: SEQUENCE SET; Schema: _timescaledb_config; Owner: irrigation_user
--

SELECT pg_catalog.setval('_timescaledb_config.bgw_job_id_seq', 1000, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: irrigation_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: irrigation_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: irrigation_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 56, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: irrigation_user
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: irrigation_user
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: irrigation_user
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: devices_id_seq; Type: SEQUENCE SET; Schema: public; Owner: irrigation_user
--

SELECT pg_catalog.setval('public.devices_id_seq', 3, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: irrigation_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: irrigation_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 13, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: irrigation_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 30, true);


--
-- Name: greenhouse_config_id_seq; Type: SEQUENCE SET; Schema: public; Owner: irrigation_user
--

SELECT pg_catalog.setval('public.greenhouse_config_id_seq', 2, true);


--
-- Name: path_cells_id_seq; Type: SEQUENCE SET; Schema: public; Owner: irrigation_user
--

SELECT pg_catalog.setval('public.path_cells_id_seq', 40, true);


--
-- Name: sensor_data_id_seq; Type: SEQUENCE SET; Schema: public; Owner: irrigation_user
--

SELECT pg_catalog.setval('public.sensor_data_id_seq', 1, true);


--
-- Name: sensor_measurements_id_seq; Type: SEQUENCE SET; Schema: public; Owner: irrigation_user
--

SELECT pg_catalog.setval('public.sensor_measurements_id_seq', 256, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: devices devices_pkey; Type: CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT devices_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: greenhouse_config greenhouse_config_pkey; Type: CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.greenhouse_config
    ADD CONSTRAINT greenhouse_config_pkey PRIMARY KEY (id);


--
-- Name: greenhouses greenhouses_pkey; Type: CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.greenhouses
    ADD CONSTRAINT greenhouses_pkey PRIMARY KEY (id);


--
-- Name: watering_cycle irrigation_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.watering_cycle
    ADD CONSTRAINT irrigation_plans_pkey PRIMARY KEY (id);


--
-- Name: path_cells path_cells_pkey; Type: CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.path_cells
    ADD CONSTRAINT path_cells_pkey PRIMARY KEY (id);


--
-- Name: path_cells path_cells_row_column_fce07728_uniq; Type: CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.path_cells
    ADD CONSTRAINT path_cells_row_column_fce07728_uniq UNIQUE ("row", "column");


--
-- Name: plants plants_pkey; Type: CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.plants
    ADD CONSTRAINT plants_pkey PRIMARY KEY (id);


--
-- Name: sensor_data sensor_data_pkey; Type: CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.sensor_data
    ADD CONSTRAINT sensor_data_pkey PRIMARY KEY (id);


--
-- Name: devices unique_device_per_greenhouse; Type: CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT unique_device_per_greenhouse UNIQUE (greenhouse_id, zigbee_id);


--
-- Name: watering_plans watering_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.watering_plans
    ADD CONSTRAINT watering_plans_pkey PRIMARY KEY (id);


--
-- Name: _hyper_2_1_chunk_idx_sensor_measurements_device_ts; Type: INDEX; Schema: _timescaledb_internal; Owner: irrigation_user
--

CREATE INDEX _hyper_2_1_chunk_idx_sensor_measurements_device_ts ON _timescaledb_internal._hyper_2_1_chunk USING btree (device_name, "timestamp" DESC);


--
-- Name: _hyper_2_1_chunk_idx_sensor_measurements_ts; Type: INDEX; Schema: _timescaledb_internal; Owner: irrigation_user
--

CREATE INDEX _hyper_2_1_chunk_idx_sensor_measurements_ts ON _timescaledb_internal._hyper_2_1_chunk USING btree ("timestamp" DESC);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: devices_greenhouse_id_db3aca3d; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX devices_greenhouse_id_db3aca3d ON public.devices USING btree (greenhouse_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: idx_sensor_device_timestamp; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX idx_sensor_device_timestamp ON public.sensor_data USING btree (device_name, "timestamp" DESC);


--
-- Name: idx_sensor_measurements_device_ts; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX idx_sensor_measurements_device_ts ON public.sensor_measurements USING btree (device_name, "timestamp" DESC);


--
-- Name: idx_sensor_measurements_ts; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX idx_sensor_measurements_ts ON public.sensor_measurements USING btree ("timestamp" DESC);


--
-- Name: idx_sensor_timestamp; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX idx_sensor_timestamp ON public.sensor_data USING btree ("timestamp" DESC);


--
-- Name: ix_greenhouses_active; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX ix_greenhouses_active ON public.greenhouses USING btree (active);


--
-- Name: ix_greenhouses_name; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX ix_greenhouses_name ON public.greenhouses USING btree (name);


--
-- Name: ix_irrigation_plans_scheduled_time; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX ix_irrigation_plans_scheduled_time ON public.watering_cycle USING btree (scheduled_time);


--
-- Name: ix_irrigation_plans_status; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX ix_irrigation_plans_status ON public.watering_cycle USING btree (status);


--
-- Name: ix_plants_active; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX ix_plants_active ON public.plants USING btree (active);


--
-- Name: ix_plants_name; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX ix_plants_name ON public.plants USING btree (name);


--
-- Name: ix_plants_planting_date; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX ix_plants_planting_date ON public.plants USING btree (planting_date);


--
-- Name: ix_watering_cycle_plan_id; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX ix_watering_cycle_plan_id ON public.watering_cycle USING btree (plan_id);


--
-- Name: ix_watering_plans_active; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX ix_watering_plans_active ON public.watering_plans USING btree (active);


--
-- Name: ix_watering_plans_name; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX ix_watering_plans_name ON public.watering_plans USING btree (name);


--
-- Name: path_cells_row_294f35_idx; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX path_cells_row_294f35_idx ON public.path_cells USING btree ("row", "column");


--
-- Name: watering_plans_greenhouse_config_id_16dd003a; Type: INDEX; Schema: public; Owner: irrigation_user
--

CREATE INDEX watering_plans_greenhouse_config_id_16dd003a ON public.watering_plans USING btree (greenhouse_config_id);


--
-- Name: sensor_measurements ts_insert_blocker; Type: TRIGGER; Schema: public; Owner: irrigation_user
--

CREATE TRIGGER ts_insert_blocker BEFORE INSERT ON public.sensor_measurements FOR EACH ROW EXECUTE FUNCTION _timescaledb_functions.insert_blocker();


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: devices devices_greenhouse_id_db3aca3d_fk_greenhouse_config_id; Type: FK CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT devices_greenhouse_id_db3aca3d_fk_greenhouse_config_id FOREIGN KEY (greenhouse_id) REFERENCES public.greenhouse_config(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: watering_cycle watering_cycle_plan_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.watering_cycle
    ADD CONSTRAINT watering_cycle_plan_id_fk FOREIGN KEY (plan_id) REFERENCES public.watering_plans(id) ON DELETE SET NULL;


--
-- Name: watering_plans watering_plans_greenhouse_config_id_16dd003a_fk_greenhous; Type: FK CONSTRAINT; Schema: public; Owner: irrigation_user
--

ALTER TABLE ONLY public.watering_plans
    ADD CONSTRAINT watering_plans_greenhouse_config_id_16dd003a_fk_greenhous FOREIGN KEY (greenhouse_config_id) REFERENCES public.greenhouse_config(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

