# Generated by Django 4.2.7 on 2026-05-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0012_greenhouse_smart_suggestions_flag'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='device',
            name='unique_device_per_greenhouse',
        ),
        migrations.RemoveField(
            model_name='greenhouseconfig',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='greenhouseconfig',
            name='location',
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='greenhouseconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('greenhouse', 'zigbee_id')},
        ),
    ]
