# Generated by Django 4.2.7 on 2026-05-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0013_remove_location_is_active_from_greenhouse_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhouseconfig',
            name='selected',
            field=models.BooleanField(default=False, help_text='Izvēlētā siltumnīca'),
        ),
    ]
