# Generated by Django 4.2.7 on 2026-05-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0014_add_selected_to_greenhouse_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhouseconfig',
            name='greenhouse_id',
            field=models.CharField(blank=True, db_index=True, help_text='Saistītās siltumnīcas ID', max_length=255, null=True),
        ),
    ]
