# Generated by Django 4.2.7 on 2026-05-13 20:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0015_add_greenhouse_id_to_greenhouse_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_key', models.CharField(help_text="Machine-readable key, e.g. 'irrigation_controller'", max_length=40, unique=True)),
                ('name', models.CharField(help_text='Human-readable name', max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'device_types',
                'ordering': ['type_key'],
            },
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['device_type__type_key', 'name']},
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(blank=True, db_column='device_type_id', help_text='Type of device', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='irrigation.devicetype'),
        ),
    ]
