# Generated by Django 4.2.7 on 2026-05-13 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0016_add_device_types_and_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='device',
            field=models.ForeignKey(blank=True, db_column='device_id', help_text='Device that produced this reading', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_readings', to='irrigation.device'),
        ),
    ]
