# Generated by Django 4.2.7 on 2026-05-13 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0017_link_sensor_data_to_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='wateringcycle',
            name='greenhouse_config',
            field=models.ForeignKey(blank=True, db_column='greenhouse_config_id', help_text='Greenhouse configuration this cycle belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watering_cycles', to='irrigation.greenhouseconfig'),
        ),
    ]
