# Generated by Django 4.2.7 on 2026-05-13 21:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0018_link_watering_cycle_to_greenhouse_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='greenhouse_id',
            field=models.CharField(blank=True, db_index=True, help_text='Saistītās siltumnīcas ID', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greenhouse_id', models.CharField(db_index=True, help_text='Linked greenhouse ID', max_length=255)),
                ('name', models.CharField(help_text='Season name', max_length=120)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'seasons',
                'ordering': ['greenhouse_id', '-is_active', 'name'],
                'unique_together': {('greenhouse_id', 'name')},
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='season',
            field=models.ForeignKey(blank=True, db_column='season_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants', to='irrigation.season'),
        ),
    ]
