# Generated by Django 4.2.7 on 2026-04-22 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationPlan',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('scheduled_time', models.DateTimeField()),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('device', models.CharField(choices=[('0x540f57fffe890af8', '🏠 Main Irrigation Controller (0x540f57fffe890af8)')], default='0x540f57fffe890af8', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'irrigation_plans',
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(help_text='Name of the sensor device', max_length=100)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Temperature in Celsius', max_digits=5, null=True)),
                ('humidity', models.IntegerField(blank=True, help_text='Humidity percentage', null=True)),
                ('linkquality', models.IntegerField(blank=True, help_text='Signal strength', null=True)),
                ('max_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_unit', models.CharField(default='celsius', max_length=20)),
                ('raw_data', models.JSONField(blank=True, help_text='Raw JSON data from sensor', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the sensor reading was taken')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the record was created')),
            ],
            options={
                'db_table': 'sensor_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device_name', '-timestamp'], name='sensor_data_device__8448a6_idx'), models.Index(fields=['-timestamp'], name='sensor_data_timesta_ac587d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Auga nosaukums vai šķirne', max_length=100)),
                ('variety', models.CharField(blank=True, help_text='Specifiskā šķirne', max_length=100, null=True)),
                ('planting_date', models.DateField(help_text='Stādīšanas datums')),
                ('watering_frequency', models.PositiveIntegerField(default=1, help_text='Laistīšanas biežums (reizes dienā)')),
                ('watering_duration', models.PositiveIntegerField(default=300, help_text='Laistīšanas ilgums sekundēs')),
                ('water_amount_ml', models.PositiveIntegerField(blank=True, help_text='Ūdens daudzums ml', null=True)),
                ('harvest_date_estimate', models.DateField(blank=True, help_text='Ražas prognozes datums', null=True)),
                ('harvest_quantity_estimate', models.FloatField(blank=True, help_text='Prognozētais ražas daudzums (kg)', null=True)),
                ('location_row', models.PositiveIntegerField(help_text='Rindas numurs siltumnīcā')),
                ('location_column', models.PositiveIntegerField(help_text='Kolonnas numurs siltumnīcā')),
                ('location_description', models.CharField(blank=True, help_text='Papildu atrašanās vietas apraksts', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, help_text='Papildu piezīmes par augu', null=True)),
                ('active', models.BooleanField(default=True, help_text='Vai augs vēl ir aktīvs')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Reģistrācijas datums')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Pēdējās izmaiņas')),
            ],
            options={
                'db_table': 'plants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', 'active'], name='plants_name_fee79a_idx'), models.Index(fields=['location_row', 'location_column'], name='plants_locatio_13b488_idx'), models.Index(fields=['-planting_date'], name='plants_plantin_121542_idx')],
            },
        ),
    ]
