# Generated by Django 4.2.7 on 2026-04-22 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField(help_text='Rindas numurs siltumnīcā')),
                ('column', models.PositiveIntegerField(help_text='Kolonnas numurs siltumnīcā')),
                ('description', models.CharField(blank=True, help_text='Ceļa apraksts', max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'path_cells',
                'ordering': ['row', 'column'],
                'indexes': [models.Index(fields=['row', 'column'], name='path_cells_row_294f35_idx')],
                'unique_together': {('row', 'column')},
            },
        ),
    ]
