apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb-postgres
    type: postgres
    access: proxy
    isDefault: true
    editable: true
    url: postgres:5432
    user: irrigation_user
    secureJsonData:
      password: irrigation_pass
    jsonData:
      database: irrigation_db
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
